[project]
name = "smart-lock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ludihan", email = "65617704+ludihan@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
smart-lock = "smart_lock:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
